SELECT * FROM HR.EMPLOYEES;

SELECT JOB_ID,
COUNT(*)  AS headcount,
SUM(SALARY) AS dept_total
FROM HR.EMPLOYEES
GROUP BY JOB_ID,MANAGER_ID
ORDER BY DEPT_TOTAL DESC;

ORDER BY COMMISSION_PCT DESC NULLS LAST;

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;

SELECT FIRST_NAME,SALARY
FROM HR.EMPLOYEES
ORDER BY SALARY DESC
FETCH FIRST 5 ROWS ONLY;

SELECT FIRST_NAME,SALARY,DEPARTMENT_ID,COMMISSION_PCT FROM HR.EMPLOYEES
ORDER BY COMMISSION_PCT DESC NULLS LAST;

SELECT CHANNEL_ID,SUM(AMOUNT_SOLD) FROM SH.SALES GROUP BY CHANNEL_ID ORDER BY AMOUNT_SOLD DESC;


SELECT COUNTRY_TOTAL FROM SH.COUNTRIES GROUP BY COUNTRY_NAME;

SELECT SUM(COUNTRY_TOTAL) FROM SH.COUNTRIES GROUP BY COUNTRY_NAME;

SELECT CUST_FIRST_NAME,CUST_CITY,CUST_STATE_PROVINCE FROM SH.CUSTOMERS;

 SELECT C1.CUST_FIRST_NAME,C1.CUST_CITY , C2.COUNTRY_NAME FROM SH.CUSTOMERS C1
 JOIN 
 SH.COUNTRIES C2 
 ON C1.COUNTRY_ID = C2.COUNTRY_ID;

SELECT PROD_ID,TIME_ID ,SUM(UNIT_PRICE)
OVER
(PARTITION BY CHANNEL_ID ORDER BY UNIT_PRICE) AS SUMMATION;

SELECT C1.AMOUNT_SOLD ,C2.COUNTRY_NAME FROM 
SH.SALES C1
JOIN
SH.CUSTOMERS C3 ON C1.CUST_ID = C3.CUST_ID;

SELECT SUM(C1.AMOUNT_SOLD),C2.COUNTRY_NAME
FROM SH.SALES C1
JOIN
SH.CUSTOMERS C3
ON
C1.CUST_ID = C3.CUST_ID
JOIN
SH.COUNTRIES C2
ON C3.COUNTRY_ID = C2.COUNTRY_ID
GROUP BY C2.COUNTRY_NAME;

SELECT C1.PROD_NAME , C1.PROD_CATEGORY,SUM(C2.AMOUNT_SOLD) FROM 
SH.PRODUCTS C1
JOIN
SH.SALES C2
ON C1.PROD_ID = C2.PROD_ID
GROUP BY C1.PROD_NAME,C1.PROD_CATEGORY;

SELECT SUM(C1.AMOUNT_SOLD),C2.CUST_FIRST_NAME FROM
SH.SALES C1
JOIN
SH.CUSTOMERS C2
ON C1.CUST_ID = C2.CUST_ID
GROUP BY C1.CHANNEL_ID
ORDER BY C1.AMOUNT_SOLD DESC
FETCH FIRST 10 ROWS ONLY;

SELECT AVG(C1.AMOUNT_SOLD),C2.COUNTRY_NAME
FROM SH.SALES C1
JOIN
SH.CUSTOMERS C3
ON
C1.CUST_ID = C3.CUST_ID
JOIN
SH.COUNTRIES C2
ON C3.COUNTRY_ID = C2.COUNTRY_ID
GROUP BY C2.COUNTRY_NAME;

SELECT C1.PROD_NAME , C1.PROD_CATEGORY,SUM(C2.AMOUNT_SOLD) FROM 
SH.PRODUCTS C1
JOIN
SH.SALES C2
ON C1.PROD_ID = C2.PROD_ID
GROUP BY C1.PROD_NAME,C1.PROD_CATEGORY;


SELECT C2.CUST_FIRST_NAME,C1.COUNTRY_NAME,C3.AMOUNT_SOLD
FROM
SH.COUNTRIES C1
JOIN
SH.CUSTOMERS C2
ON C1.COUNTRY_ID = C2.COUNTRY_ID
JOIN
SH.SALES C3
ON C3.CUST_ID = C2.CUST_ID
WHERE
C3.AMOUNT_SOLD IS NULL;

SELECT * FROM SH.SALES WHERE AMOUNT_SOLD IS NULL;

SELECT EMPLOYEE_ID, salary
FROM HR.EMPLOYEES
WHERE salary > (SELECT AVG(salary) FROM HR.employees);
